[package]
name = "simple-tunnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
log = "0.4"
structopt = "0.3"

[dependencies.tokio]
version = "1.29"
features = [ "full" ]
